version: 2.1

orbs:
  codecov: codecov/codecov@3.3.0

jobs:
  pre-commit:
    parameters:
      config_file:
        default: ./.pre-commit-config.yaml
        description: Optional, path to pre-commit config file.
        type: string
      cache_prefix:
        default: ''
        description: |
          Optional cache prefix to be used on CircleCI. Can be used for cache busting or to ensure multiple jobs use different caches.
        type: string
    docker:
      - image: speckle/pre-commit-runner:latest
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-pre-commit-<<parameters.cache_prefix>>-{{ checksum "<<parameters.config_file>>" }}
      - run:
          name: Install pre-commit hooks
          command: pre-commit install-hooks --config <<parameters.config_file>>
      - save_cache:
          key: cache-pre-commit-<<parameters.cache_prefix>>-{{ checksum "<<parameters.config_file>>" }}
          paths:
            - ~/.cache/pre-commit
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files
      - run:
          command: git --no-pager diff
          name: git diff
          when: on_fail

  test:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: false
    resource_class: medium
    parameters:
      tag:
        default: "3.11"
        type: string
    steps:
      - checkout
      - run:
          name: Install python
          command: |
            pyenv install -s << parameters.tag >>
            pyenv global << parameters.tag >>
      - run:
          name: Startup the Speckle Server
          command: docker compose -f docker-compose.yml up -d
      - run:
          name: Install Poetry
          command: |
            pip install poetry
      - run:
          name: Install packages
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest --cov --cov-report xml:reports/coverage.xml --junitxml=reports/test-results.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - codecov/upload

  deploy:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout
      - run: python patch_version.py $CIRCLE_TAG
      - run: poetry build
      - run: poetry publish -u __token__ -p $PYPI_TOKEN

workflows:
  main:
    jobs:
      - pre-commit:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              tag: ["3.11"]
          filters:
            tags:
              only: /.*/
      - deploy:
          context: pypi
          requires:
            - pre-commit
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/ # For testing only! /ci\/.*/
